name: Issue
description: for reporting any issue
labels: ["ISSUE"]
body:
  - type: markdown
    attributes:
      value: "**Welcome to submit a new issue!**\n- Please search in [existing issues](https://github.com/ladybug-me/end-4dotsKDE/issues?q=is%3Aissue) before continuing.\n- It takes only 3 steps, thanks for your patience :)\n- NOTE 1: General questions like \"how do I customize this widget\" should use [Discussions](https://github.com/ladybug-me/end-4dotsKDE/discussions) instead.\n- NOTE 2: This is a **KDE Plasma port**. For Hyprland issues, see [end-4/dots-hyprland](https://github.com/end-4/dots-hyprland)."
  - type: checkboxes
    attributes:
      label: "Step 1. Before you submit"
      description: "Hint: The 2nd and 3rd checkbox is **not** forcely required as you may have failed to do so."
      options:
        - label: I have read the [troubleshooting guide](https://github.com/ladybug-me/end-4dotsKDE#troubleshooting) and checked [existing discussions](https://github.com/ladybug-me/end-4dotsKDE/discussions).
          required: true
        - label: I've pulled the latest changes and re-run the installer (`bash ./setup.sh`).
          required: false # Not required cuz user may have failed to do so
        - label: I've successfully updated system packages with `sudo pacman -Syu`.
          required: false # Not required cuz user may have failed to do so
        - label: I've ticked the checkboxes without reading their contents
          required: false # Obviously
  # TODO: Use GitHub Action to auto add folding tag if the log contains more than 15 lines, instead of tell user to "paste here" cuz many users actually does not know its meaning (It's also not convenient anyway).
  - type: textarea
    attributes:
      label: "Step 2. Quick diagnose info"
      description: "Run `./diagnose` inside the repo, and paste the result (which is also saved as file `./diagnose.result`) below."
      value: "<details><summary>Quick diagnose</summary>\n\n```\n<!-- Run `./diagnose` inside the repo, and paste the result here! -->\n```\n\n</details>"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Tips for the following Step 3**
        1. Use `LANG=C LC_ALL=C` to get the output of a command in English, eg. `LANG=C LC_ALL=C date` displays time in English.
        2. If it throws errors, **PLEASE**, attach logs and describe in detail if possible.
           - Bar and widgets not showing? run `pkill qs; qs -c ii` for logs.
           - Installation failed? Run installation again for logs.
           - You may use more code blocks when needed.
        3. In case you are confused, the `<details>`, `<summary>`, `</summary>`, `</details>` are HTML tags for folding the logs (typically very long) inside. Please do not touch them (unless you know what you are doing).
        4. If the logs are suuuuuuper long, consider using an online pastebin service instead.

  - type: textarea
    attributes:
      label: "Step 3. Describe the issue"
      value: "\n<!-- Firsly describe your issue here! -->\n\n<details><summary>Logs</summary>\n\n```\n<!-- Put your log content here!-->\n```\n\n</details>"
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Reminder
      options:
        - label: I agree that it's usually impossible for others to help me without my logs.
          required: true
